services:
  silverbullet:
    image: zefhemel/silverbullet:latest
    container_name: silverbullet
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - silverbullet_space:/space

volumes:
  silverbullet_space:
    name: silverbullet-space
